In [1]:
import pandas as pd

In [10]:
tanks = pd.read_csv("../data/assets/tanks.csv")

In [3]:
tanks

,wg_id,tag,lvl,type,name,short_name,damage,dpm,penetration,accuracy,aim_time,speed,cp_power,hp,armor_hull,armor_turret,view_range,wr_id
0,1,R04_T-34,5,mediumTank,Т-34,Т-34,85,2217.65,112,0.34,2.3,56,17.40,590,45,52.0,350,467-795
1,3137,F08_AMX_50_100,8,heavyTank,AMX 50 100,AMX 50 100,240,1776.00,212,0.36,3.0,51,17.11,1400,90,90.0,380,378-858
2,2049,R12_A-20,5,lightTank,А-20,А-20,40,2168.80,46,0.45,2.3,72,28.39,560,20,37.0,360,486-1004
3,15617,R95_Object_907,10,mediumTank,Объект 907,Об. 907,320,2953.60,264,0.36,2.0,55,16.94,2000,110,228.0,400,669-1057
4,49169,G136_Tiger_131,6,heavyTank,Tiger 131,Tiger 131,220,1885.40,145,0.38,2.3,40,11.40,1060,100,100.0,370,1280
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,545,A01_T1_Cunningham,1,lightTank,T1 Cunningham,T1,30,900.00,33,0.51,2.5,41,17.47,245,10,10.0,280,1033
715,4705,J21_Type_91,3,heavyTank,Type 91 Heavy,Type 91,70,1999.90,81,0.40,2.1,25,12.44,445,20,20.0,330,892
716,47873,R143_T_29,3,mediumTank,Т-29,Т-29,110,1410.20,66,0.55,2.3,45,17.54,445,30,20.0,300,1281
717,1841,Ch18_WZ-120,9,mediumTank,WZ-120,WZ-120,440,2398.00,249,0.38,3.4,60,16.13,1750,100,220.0,390,617
718,5169,Ch20_Type58,6,mediumTank,Type 58,Type 58,160,1920.00,128,0.38,2.3,55,16.00,840,45,90.0,370,626

In [11]:
# Label encoding "type" column
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(tanks.type.unique())
tanks["type_le"] = le.transform(tanks.type)
tanks

,wg_id,tag,lvl,type,name,short_name,damage,dpm,penetration,accuracy,aim_time,speed,cp_power,hp,armor_hull,armor_turret,view_range,wr_id,type_le
0,1,R04_T-34,5,mediumTank,Т-34,Т-34,85,2217.65,112,0.34,2.3,56,17.40,590,45,52.0,350,467-795,4
1,3137,F08_AMX_50_100,8,heavyTank,AMX 50 100,AMX 50 100,240,1776.00,212,0.36,3.0,51,17.11,1400,90,90.0,380,378-858,2
2,2049,R12_A-20,5,lightTank,А-20,А-20,40,2168.80,46,0.45,2.3,72,28.39,560,20,37.0,360,486-1004,3
3,15617,R95_Object_907,10,mediumTank,Объект 907,Об. 907,320,2953.60,264,0.36,2.0,55,16.94,2000,110,228.0,400,669-1057,4
4,49169,G136_Tiger_131,6,heavyTank,Tiger 131,Tiger 131,220,1885.40,145,0.38,2.3,40,11.40,1060,100,100.0,370,1280,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,545,A01_T1_Cunningham,1,lightTank,T1 Cunningham,T1,30,900.00,33,0.51,2.5,41,17.47,245,10,10.0,280,1033,3
715,4705,J21_Type_91,3,heavyTank,Type 91 Heavy,Type 91,70,1999.90,81,0.40,2.1,25,12.44,445,20,20.0,330,892,2
716,47873,R143_T_29,3,mediumTank,Т-29,Т-29,110,1410.20,66,0.55,2.3,45,17.54,445,30,20.0,300,1281,4
717,1841,Ch18_WZ-120,9,mediumTank,WZ-120,WZ-120,440,2398.00,249,0.38,3.4,60,16.13,1750,100,220.0,390,617,4
718,5169,Ch20_Type58,6,mediumTank,Type 58,Type 58,160,1920.00,128,0.38,2.3,55,16.00,840,45,90.0,370,626,4

In [12]:
# If tank has no turret set hull armor as turret armor
tanks.armor_turret = tanks.armor_turret.fillna(tanks.armor_hull)
tanks = tanks.convert_dtypes()
tanks

,wg_id,tag,lvl,type,name,short_name,damage,dpm,penetration,accuracy,aim_time,speed,cp_power,hp,armor_hull,armor_turret,view_range,wr_id,type_le
0,1,R04_T-34,5,mediumTank,Т-34,Т-34,85,2217.65,112,0.34,2.3,56,17.4,590,45,52,350,467-795,4
1,3137,F08_AMX_50_100,8,heavyTank,AMX 50 100,AMX 50 100,240,1776.0,212,0.36,3.0,51,17.11,1400,90,90,380,378-858,2
2,2049,R12_A-20,5,lightTank,А-20,А-20,40,2168.8,46,0.45,2.3,72,28.39,560,20,37,360,486-1004,3
3,15617,R95_Object_907,10,mediumTank,Объект 907,Об. 907,320,2953.6,264,0.36,2.0,55,16.94,2000,110,228,400,669-1057,4
4,49169,G136_Tiger_131,6,heavyTank,Tiger 131,Tiger 131,220,1885.4,145,0.38,2.3,40,11.4,1060,100,100,370,1280,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,545,A01_T1_Cunningham,1,lightTank,T1 Cunningham,T1,30,900.0,33,0.51,2.5,41,17.47,245,10,10,280,1033,3
715,4705,J21_Type_91,3,heavyTank,Type 91 Heavy,Type 91,70,1999.9,81,0.4,2.1,25,12.44,445,20,20,330,892,2
716,47873,R143_T_29,3,mediumTank,Т-29,Т-29,110,1410.2,66,0.55,2.3,45,17.54,445,30,20,300,1281,4
717,1841,Ch18_WZ-120,9,mediumTank,WZ-120,WZ-120,440,2398.0,249,0.38,3.4,60,16.13,1750,100,220,390,617,4
718,5169,Ch20_Type58,6,mediumTank,Type 58,Type 58,160,1920.0,128,0.38,2.3,55,16.0,840,45,90,370,626,4

In [9]:
# Clustering function
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

def cluster(n, lvl=None):
    if lvl is None:
        filter_ = [True] * len(tanks)
    else:
        filter_ = tanks.lvl == lvl
    y_pred = KMeans(n_clusters=n, random_state=42).fit_predict(
        StandardScaler().fit_transform(
            tanks[filter_].drop(
                ["wg_id", "wr_id", "tag", "name", "short_name", "type"], axis=1)
        )
    )
    return pd.Series(data=[i if lvl is None else f"l{lvl}_{i}" for i in y_pred], index=tanks[filter_].tag)\
        .reset_index().rename(columns={0:"cluster"})

In [7]:
from sklearn.manifold import TSNE
import plotly.express as px

def plot_clusters(pred, lvl=None):
    if lvl is None:
        filter_ = [True] * len(tanks)
    else:
        filter_ = tanks.lvl == lvl

    vects = StandardScaler().fit_transform(
        tanks[filter_].drop(
            ["wg_id", "wr_id", "tag", "name", "short_name", "type"], axis=1)
    )

    vects_tsne = TSNE(n_components=2, verbose=50).fit_transform(vects, axis=1)

    fig = px.scatter(
        x=vects_tsne[:, 0],
        y=vects_tsne[:, 1],
        color=list(pred),
        hover_data=[tanks[filter_].name, pred,
                    tanks[filter_].level, tanks[filter_].type]
    )

    fig.show()

tag
R04_T-34                l5_1
R12_A-20                l5_1
GB51_Excelsior          l5_3
F22_AMX_105AM           l5_2
J08_Chi_Nu              l5_1
                        ...
F62_ELC_AMX             l5_1
G104_Stug_IV            l5_3
J12_Chi_Nu_Kai          l5_1
G107_PzKpfwIII_AusfK    l5_1
GB60_Covenanter         l5_0
Length: 66, dtype: object

In [ ]:
all_ = cluster(10)